package db연결;

public class 예외처리2 {

	public static void main(String[] args) throws Exception{
	
			int[] num = {1, 2, 3};
			num[3] = 4;
			

		
		System.out.println("나는실행 될까말까");
	}

}
